// Generated by tools/export_economy_catalog.dart. Do not edit by hand.
const int economyCatalogSchemaVersion = 1;
const int economyCatalogEventCount = 550;
const String economyCatalogContentHash =
    'fbfb1390d60accfdcc46357ff121e403367b69930ebfb77336143c2fd152e0a5';
const String economyCatalogVersion =
    'v$economyCatalogSchemaVersion:$economyCatalogEventCount:$economyCatalogContentHash';
