// Generated by tools/export_economy_catalog.dart. Do not edit by hand.
const int economyCatalogSchemaVersion = 1;
const int economyCatalogEventCount = 550;
const String economyCatalogContentHash =
    '28a8741b4eace13093913a5be1ea436bc6cbd08860d0ee619be7863f12cf9cd2';
const String economyCatalogVersion =
    'v$economyCatalogSchemaVersion:$economyCatalogEventCount:$economyCatalogContentHash';
