// Generated by tools/export_economy_catalog.dart. Do not edit by hand.
const int economyCatalogSchemaVersion = 1;
const int economyCatalogEventCount = 550;
const String economyCatalogContentHash =
    '0b13374a139597430e4f1c4b86e97865208bb8a369346d8d87779cb82ec8ea19';
const String economyCatalogVersion =
    'v$economyCatalogSchemaVersion:$economyCatalogEventCount:$economyCatalogContentHash';
